packages:
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - happy-dom
  - '@rolldown/*'
  - '@typescript/native-preview*'

onlyBuiltDependencies:
  - esbuild
