name: CI

on:
  push:
    branches: [main, alpha]
  pull_request:
    branches: [main, alpha]

permissions: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install dependencies
        uses: $/.github/actions/install

      - name: Run build
        run: pnpm build

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
