name: Publish

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  build-artifacts:
    if: github.repository == 'grlt-hub/react-slots'
    name: Build package tarballs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      npm_tag: ${{ steps.release.outputs.npm_tag }}
    steps:
      - name: Install dependencies
        uses: $/.github/actions/install

      - name: Pack packages
        run: |
          mkdir -p "$GITHUB_WORKSPACE/package-tarballs"
          pnpm --filter './packages/*' -r pack --pack-destination "$GITHUB_WORKSPACE/package-tarballs"

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Resolve publish tag
        id: release
        run: node scripts/resolve-publish-tag.ts "${GITHUB_REF_NAME}" npm_tag

      - name: Upload package tarballs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package-tarballs
          path: package-tarballs/*.tgz
          if-no-files-found: error
          retention-days: 1

  publish:
    if: github.repository == 'grlt-hub/react-slots'
    name: Stage packages
    needs: build-artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download package tarballs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: package-tarballs
          path: package-tarballs

      - name: Set node version to 26
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          package-manager-cache: false

      - name: Stage packages
        env:
          NPM_TAG: ${{ needs['build-artifacts'].outputs.npm_tag }}
        run: node scripts/publish-ci.ts ./package-tarballs "${NPM_TAG}"
